### ISSUE TITLE
Error Calling Module

### ISSUE THREAD

**Issue by developer-evan** [gohugoio/hugo-mod-jslibs#4]
I just did, what you said in the readme file. but end up with this error

error calling partial: "E:\OFFICE\Hugo\reader\layouts\partials\head.html:30:5": execute of template failed: template: partials/head.html:30:5: executing "partials/head.html" at <partialCached "jslibs/alpinejs/script-src.html" "-">: error calling partialCached: partial "jslibs/alpinejs/script-src.html" not found

Don't know what I am doing wrong....

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
